backend:
  name: git-gateway
  branch: master 
media_folder: "/assets/post_img" 
display_url: https://lbjheiheihei.xyz
locale: 'zh-cn'
collections: 
- name: "post" 
  label: "发表" 
  folder: "/_posts" 
  sort: "date:desc" 
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields: 
    - {label: "链接", name: "permalink", widget: "string", default: "/YYYY/MM/DD/英文的文章描述.html", required: true}
    - {label: "标题", name: "title", widget: "string", tagname: "h1"}
    - {label: "描述", name: "subtitle", widget: "string", tagname: "h3"}
    - {label: "背景图", name: "cover", widget: "image",required: false}
    - {label: "作者", name: "author", default: "君子", widget: "string"}
    - {label: "Tags", name: "tags", widget: "string", required: false}
    - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
    - {label: "正文", name: "body", widget: "markdown"}
    - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
page: 
  enabled: true
  config:
    label: "Page"
    delete: false