backend:
  name: git-gateway
  branch: master 
publish_mode: editorial_workflow
media_folder: "/assets/img" 
collections: 
- name: "post" 
  label: "Post" 
  folder: "/_posts" 
  sort: "date:desc" 
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields: 
    - {label: "Permalink", name: "permalink", widget: "string", default: "/YYYY/MM/DD/root", required: false}
    - {label: "Title", name: "title", widget: "string", tagname: "h1"}
    - {label: "Subtitle", name: "subtitle", widget: "string", tagname: "h3"}
    - {label: "Cover Image", name: "cover", widget: "image",required: false}
    - {label: "Author", name: "author", widget: "string"}
    - {label: "Tags", name: "tags", widget: "string", required: true}
    - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
